---
- name: RHEL8 Playbook
  hosts: all
  vars_prompt:

#    - name: "lbitc_user"
#      prompt: "Enter your  lbitc username"
#      private: no
#
#    - name: "lbitc_token"
#      prompt: "Enter your lbitc login token"
#      private: yes
#

#    - name: "ansible_http_lbitc_username"
#      prompt: "Enter You lbitc UserID"
#      private: no
#
#    - name: "ansible_http_lbitc_password"
#      prompt: "Enter your lbitc login password"
#      private: yes
#
   
  roles:
    - { role: dns, 		tags: [ 'os', 'dns' ]	 } 
    - { role: users, 		tags: [ 'os', 'users' ]	 }
    - { role: apache, 		tags: [ 'os', 'apache' ] }
    - { role: chrony, 		tags: [ 'os', 'chrony' ] }
    - { role: git, 		tags: [ 'os', 'git' ]	 }
