---

- name: Unneeded Accounts set to NoLogin
  become: yes
  user:
    name: "{{ item }}"
    shell: /sbin/nologin
  loop:
    - "sync"
    - "shutdown"
    - "halt"
    - "mysql"
    - "polo"

# CIS 5.4.1.1 - 5.4.1.3
- name: Enforce password aging
  become: yes
  lineinfile: dest=/etc/login.defs
              state=present
              regexp="{{item.regex}}"
              line="{{item.line}}"
  with_items:          
    - { regex: '^PASS_MAX_DAYS.*$', line: 'PASS_MAX_DAYS 90' }
    - { regex: '^PASS_MIN_DAYS.*$', line: 'PASS_MIN_DAYS 7' }
    - { regex: '^PASS_WARN_AGE.*$', line: 'PASS_WARN_AGE 7' }

# CIS 5.4.1.4
- name: Ensure inactive password lock is 30 days or less
  become: yes
  shell: useradd -D -f 30

# CIS 5.4.1.1 - 5.4.1.4 (Continued...)
- name: Enforce account inactivation after password expiration
  become: yes
  shell: cat /etc/passwd | awk -F":" '( $3 >=500 && $1 != "nfsnobody" ) { print $1 }' | xargs -n 1 chage --{{item}}
  with_items:
    - "warndays 7"
    - "maxdays 90"
    - "mindays 7"
    - "inactive 30"

# Required for CIS 6.1.6
- name: /etc/passwd- permissions
  become: yes
  file:
    path: /etc/passwd-
    owner: root
    group: root
    mode: 600

# Required for CIS 6.1.8
- name: /etc/group- permissions
  become: yes
  file:
    path: /etc/group-
    owner: root
    group: root
    mode: 600


# CIS 6.2.6 (Workaround) 
- name: Ensure root PATH Integrity
  become: yes
  file: path=/root/bin
        mode=700
        state=directory
