---
- name: lbitc-admins group
  become: yes
  group:
    name: lbitc-admins
    state: present

- name: User account
  become: yes
  user:
    name: "{{ item.username }}"
    groups: lbitc-admins
    state: present
  loop: "{{ users }}"

- name: SSH keys for users
  become: yes
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ users }}"

- name: Allow 'lbitc-admins' group to sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%lbitc-admins'
    line: '%lbitc-admins ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
